const:
  default-page-size: 20

file:
  directory: D:/ksj/download/greengram_ver3

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3  #??? DB? jdbc? log4jdbc? mariadb? ???.
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true